version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    # Update this at new releases to target whatever the current dev branch is
    target-branch: "dev/30-howlite"
    labels:
      - "dependencies"