language: node_js
node_js:
  - '12.11.1'
  - '12'
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn test:ci

jobs:
  include:
    - stage: publish to npm
      # only matches when a semver tag is found
      if: tag =~ ^v[0-9]+\.[0-9]+\.[0-9]+(\-.+)?
      # only run on one node (would inherit the root level multiple node_js otherwise)
      node_js: '12.11.1'
      # dont run the top level script tag above
      script: skip
      deploy:
        provider: script
        script: yarn run release:publish --yes
        on:
          tags: true
        env:
          secure: "gVlbRF7dWM8A64GKoGEVr3wganOLC+ZHvyRvuaRV4FaezWeDET0uTxxAFPdpjXLN+X8D+3LuxAG7gEyKcNBZljxavQJUjZEvG4JiiAAWZvdpMqNhhAowG7K2JgQelI1qHBoOIqPmpAwAMcnkMvFr8NBDu9si70ZDVSJqv3bQaBppZ7oAZ3xlWqmCzL98yVmkSOBGR/TYxuLK+6URXYI0C3FNxz/gXN56nbnOsOS16pvM7UzeuFUaz+CNk37YgS70mrSDg5IAAa6UbLcfv9eFJLS2ql4MNvedjF4Z/DzHcV3ZG7PV2ZEouIswmaeoKbVyBJ6q70yzXvgSt0Hl0KLFtD34N26mhFxunc8uMB20dQDnFQtYvpG3JP2hvzJ2iWUwB3Fm4KdiEDCAomFrWxUED4kAp+MhMC7PsSCjVmQ+mU+u1qteXGWwRnGBBg+0Q6YwZvV72L1i5I0/9ThONT5/E+9IaF9AV0RO5PqG+qX1MEJ8go6jEdkNDhnOI+AuvdqczBhKQ84/fbVeBQYPWNOjNAY6XYhtGrhEuRA1q2ypwhJgJ5aO22JOyoH7pXZMBXS3oW0S/p6tojQeb0hAB1OlgVid7W5/nUKVm0gxl2RHlVBlDIXoR65KLGordjauoox+RGUT1yeUlIoauhlsPaTxsEnkrR7CrVkJPTEIo3+PKts="
